# YOLOv11 Nano Configuration
# Latest generation, fastest model
yolo_detector_node:
  ros__parameters:
    model_path: 'yolo11n.pt'
    model_type: 'yolov11'
    device: 'cuda:0'
    confidence_threshold: 0.25
    iou_threshold: 0.45
    input_topic: '/camera/color/image_raw'
    max_det: 300
    enable_visualization: true
    publish_image: true
    image_size: 640
